
== bash のスクリプトで実行行/呼出し行の取得（行番号の取得）


[[personal-public-article-body]]
____
ファイル上の**現在の行番号を Bash のスクリプト内で取得**したい。
____

例えば Perl や PHP の「`__LINE__`」や Golang の
`_, _, line, _ := runtime.Caller(0)` のように。

他の言語では実行行の取得は分かっていたのですが、「シェルの場合は何だっけ」と
Qiita
記事に絞ってhttps://www.google.co.jp/search?q=site%3Aqiita.com+%E3%82%B7%E3%82%A7%E3%83%AB+%E7%8F%BE%E5%9C%A8%E3%81%AE%E5%AE%9F%E8%A1%8C%E8%A1%8C+%E8%A1%8C%E7%95%AA%E5%8F%B7+%E5%8F%96%E5%BE%97[「`site:qiita.com シェル 現在の実行行 行番号 取得`」とググって]もすぐに見つからなかったので、自分のググラビリティとして。


. シェル変数の「`$LINENO`」を使う。ラインナンバーの略。
. 関数の「呼び出し元の実行行」を取得したい場合は「`$BASH_LINENO`」
. 動くサンプルをおくれ。

[.bold]#sample_lineno.sh#

....
#!/bin/bash

echo $LINENO
echo $LINENO
....

[.bold]#実行結果#

....
$ ./sample_lineno.sh
3
4
....

[.bold]#sample_bash_lineno.sh#

....
#!/bin/bash

hoge () {
    echo "Called from line:${BASH_LINENO[0]}"
}

hoge
hoge
....

[.bold]#実行結果#

....
$ ./sample_bash_lineno.sh
Called from line:7
Called from line:8
....

* https://paiza.io/projects/xW0g5zcysF5E84H5g2x0Xw[オンラインで色々な動作を見る]
@ paiza.IO

=== [#動作確認済み環境 .fragment]##link:#%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D%E6%B8%88%E3%81%BF%E7%92%B0%E5%A2%83[__]動作確認済み環境

* macOS HighSierra（OSX 10.13.6）
* `bash --version`:
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`

== [#ts-dr-用途に関するコマケーこと .fragment]##link:#ts-dr-%E7%94%A8%E9%80%94%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%82%B3%E3%83%9E%E3%82%B1%E3%83%BC%E3%81%93%E3%81%A8[__]TS; DR ~^~^（用途に関するコマケーこと）^~^~

実行行の取得は、**一般的には LOG
出力に使うことが多い**と思います。しかし、今回は終了ステータスのコードを実行行にしたかったのです。

つまり、スクリプトを `exit` する際の
"`0`"（正常終了）以外の場合、通常はエラー番号（エラーコード）を "`1`"
や独自のエラーコードにするところを、「**`exit`
した行」にしたかった**のです。

[.bold]#sample.sh#

....
#!/bin/bash

dir_curr=$(cd $(dirname $0); pwd)

# Make temp directory
# -------------------
echo -n 'Now creating temporary directory ... '
dir_temp=$(mktemp -d)
if [ $? -gt 0 ]; then
    echo ' NG'
    echo '* Error while creating temp directory.'; exit $LINENO
fi
echo 'OK'

# Moving to temp directory
# ------------------------
echo -n 'Now changing work directory to temporary ... '
cd $dir_temp
if [ $? -gt 0 ]; then
    echo ' NG'
    echo '* Error while changing work to temp directory.'; exit $LINENO
fi
echo 'OK'

exit 0
....

PHP や Golang
などからシェル・スクリプトを外部コマンドとして実行した際、問題があった場合に標準エラー出力（`STDERR`）と共に、エラー番号に意味を持たせたかったのです。

しかし、*横着なため管理しきれず*、「どうせソースを見に行くんだから行番号の方が楽でいいや」と**「エラー番号
＝ エラーで抜けた行」に統一**することにしました。`_(:⁍」 )_`

**注意点**として、*bash の終了ステータス番号は１バイト*、つまり 0-255
の整数です。255 を越えると 0 から再度カウントされた値が出力されます。

つまり、`$EXIT_NUM % 256` と 256 で
https://ja.wikipedia.org/wiki/%E5%89%B0%E4%BD%99%E6%BC%94%E7%AE%97[`mod`（剰余）]
されて出力されるのです。

[.bold]#第１引数を終了ステータス番号として「exit」するだけのスクリプトでテスト#

....
$ # テスト・スクリプト
$ cat sample.sh
#!/usr/bin/env bash
exit $1

$ # テスト
$ ./sample.sh 10 ; echo $?
10

$ ./sample.sh 255 ; echo $?
255

$ ./sample.sh 256 ; echo $?
0

$ ./sample.sh 257 ; echo $?
1
....

このように、「エラー番号＝終了行」とする手法を使う場合、スクリプトは 255
行以内に抑える必要があります。偶然にも 256 行目でエラーが発生しても `0`
となり正常終了扱いになったり、256 行目以降では追跡できなくなるからです。

そのため私の場合、**スクリプトは 256
行以上になるならファイルをわける**という方針でカバーしています。

256
行以内に抑えることが難しい場合は、別のスクリプトにわけてメインのスクリプトから呼び出すことも可能です。

=== [#source-でスクリプトを-include-しても動作する .fragment]##link:#source-%E3%81%A7%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%82%92-include-%E3%81%97%E3%81%A6%E3%82%82%E5%8B%95%E4%BD%9C%E3%81%99%E3%82%8B[__]`source` でスクリプトを `include` しても動作する

別のスクリプト・ファイルにわける場合は、`source <inclueするファイルのパス>`
で可能です。その際に、`include` する側は `$BASH_LINENO`
で「呼び出し元の行番号」を取得できます。

[.bold]#sample1.sh#

....
function function1(){
  echo $BASH_LINENO
}
....

[.bold]#Main.sh#

....
#!/bin/bash

source sample1.sh
function1
....

....
./Main.sh
4
....

* https://paiza.io/projects/xW0g5zcysF5E84H5g2x0Xw[オンラインで色々な動作を見る]
@ paiza.IO

image:~/2-1/2-1_255.svg

link:/KEINOS/items/fe155839a45788518e65/likers[9]

Go to list of users who liked

image:~/2-1/2-1_261.svg

[.style-1129w32]#4#

link:#comments[[.material-symbols-outlined .style-n5k90r]##comment##0]

Go to list of comments

Register as a new user and use Qiita more conveniently

. You get articles that match your needs
. You can efficiently read back useful information
. You can use dark theme

https://help.qiita.com/ja/articles/qiita-login-user[What you can do with
signing up]

link:/signup?callback_action=login_or_signup&redirect_to=%2FKEINOS%2Fitems%2Ffe155839a45788518e65&realm=qiita[Sign
up]link:/login?callback_action=login_or_signup&redirect_to=%2FKEINOS%2Fitems%2Ffe155839a45788518e65&realm=qiita[Login]

image:~/2-1/2-1_281.svg

link:/KEINOS/items/fe155839a45788518e65/likers[9]

Go to list of users who liked

image:~/2-1/2-1_287.svg

[.style-1vem4tk]#4#

[.material-symbols-outlined .style-v2p563]#more_horiz#

Delete article

[.material-symbols-outlined .style-v2p563]#close#

Deleted articles cannot be recovered.

Draft of this article would be also deleted.

Are you sure you want to delete this article?

Cancel

Delete[.material-symbols-outlined .is-fill .style-1jvcm2e]##delete##

[[GlobalFooter-react-component-f9fa4e7b-58e1-45d8-8dce-1edcc1fbecd8]]
image:~/2-1/2-1_308.svg

How developers code is here.

[.small]#© 2011-2025[.style-15fzge]##Qiita Inc.###

Guide & Help

* link:/about[About]
* link:/terms[Terms]
* link:/privacy[Privacy]
* http://help.qiita.com/ja/articles/qiita-community-guideline[Guideline]
* https://help.qiita.com/ja/articles/others-brand-guideline[Media Kit]
* https://github.com/increments/qiita-discussions/discussions/116[Feedback/Requests]
* https://help.qiita.com[Help]
* https://business.qiita.com/?utm_source=qiita&utm_medium=referral&utm_content=footer[Advertisement]

Contents

* link:/release-notes[Release Note]
* link:/official-events[Official Event]
* link:/official-columns[Official Column]
* link:/advent-calendar/2024[Advent Calendar]
* link:/qiita-award[Qiita Award]
* link:/white_papers/2024[Engineer White Paper]
* link:/api/v2/docs[API]

Official Accounts

image:~/2-1/2-1_337.svg
image:~/2-1/2-1_338.svg
image:~/2-1/2-1_339.svg
* https://www.facebook.com/qiita/[Facebook]
* https://www.youtube.com/@qiita5366[YouTube]
* https://open.spotify.com/show/4E7yCLeCLeQUsNqM4HXFXA[Podcast]

Our service

* https://teams.qiita.com/[Qiita Team]
* https://zine.qiita.com?utm_source=qiita&utm_medium=referral&utm_content=footer[Qiita
Zine]
* https://suzuri.jp/qiita[Official Shop]

Company

* https://corp.qiita.com/company[About Us]
* https://corp.qiita.com/jobs/[Careers]
* https://blog.qiita.com[Qiita Blog]
* https://corp.qiita.com/releases/[News Release]

[[Snackbar-react-component-aca25f4f-1f9b-4824-a0a6-efaf1cbce96c]]

[[LoginModal-react-component-f55dcad7-d5c1-42ef-b538-347df5700345]]

[[dataContainer]]
