[[toc]]

1-2 shebang
[TIP]
====
#!/bin/bash
#

or 以下の方がディストリビューションによる影響を受けにくい

#!/usr/bin/env bash
#
====

1-2 変数定義
[TIP]
====
* 定数は大文字で記述(declare -r my_var (読み出し専用の変数を宣言), typeset)
* 関数は定数の後に記述
* 関数と関数の間に実行コードは書かない
====

1-2 bash起動オプション
[TIP]
====
----
#!/bin/bash

# 最初に設定
set -euC

echo "myscript"
----
* シェバンに記述可能。bashコマンド実行でオプションが機能しなくなるのでset利用が良い
** `-e`オプション
*** スクリプト中のコマンドがエラーになった場合にスクリプトを停止する +
※`grep`
`ls`などが0件になる場合に終了コード0以外になるので、一時的に`-e`を解除する必要がある

** `-u`オプション
*** 未定義変数を使おうとするとエラー終了するようになる
*** 変数名のタイプミスや初期化わすれでの変数の利用などを防ぐことができる
** `-C`オプション
*** リダイレクトでファイル上書き時にエラー終了する
*** リダイレクトでファイルを生成するときに想定外に上書きしてしまうことを防ぐことができる
*** 以下のようにすれば回避できる
====

1-4 外部スクリプト起動方法
[TIP]
====
外部スクリプトの起動方法
* `.`（ドット）コマンドで読み込む。Bashでは`source`コマンド利用。
* 「.」での実行は該当スクリプト中で記述した変数や関数は、自作のスクリプトに取込み不可。
* bashのシェルスクリプトでは、他ファイルに作成した関数をsourceで取込み可能。
====

1-4 ブレーズ変数
[TIP]
====
範囲指定で複数の範囲を指定する場合以下で可能
# 出力文字種・文字色・背景反転色確認
....
for i in {1..9} {30..37} {40..47};do
    echo  '\e[%dm%d\e[m ' $i $i
done
....
====

2-2 ログ取得、bash起動オプション
[TIP]
====
....
#!/usr/bin/env bash -
　上記「bash -」は、ログインシェルとして動作。これは、ログイン時に
　読込む/etc/profileや~/.bash_profile、~/.profile等の初期化ファイルを
　読込み、環境変数や設定をログイン時の状態として初期化し起動
....
====

2-3 ログ取得、リダイレクト方法
[TIP]
====
....
# exec はbash内部コマンドで実行中bashでリダイレクトを有効にできることに注意
# ファイル出力と標準出力・エラー出力を同時に実行する方法
exec 1> >(tee -a "$LOG_OUT")
exec 2> >(tee -a "$LOG_ERR")
....
====

3-1 サイズ指定のテキストファイル
[TIP]
====
簡易にテキスト文字列を決まったバイト数だけ作成する方法
1行100文字のテキストデータファイルを作成する方法
....
$ base64 -w 100 /dev/urandom | head -n 行数`
....
====

3-2 IFSとOFS
[TIP]
====
IFS(Internal Field Separator)は、改行や空白である。
設定変更可能で、通常はファイル内の要素を処理をしたい場合有効です。

fileinn.bash

----
#!/usr/bin/env bash

textfile=$(cat /confirm/content/of/file)
echo $textfile
----

上記はコマンド実行結果を変数に代入します。以下実行結果。

----
# fileinn.bash fileinn.bash
#!/usr/bin/env bash textfile=$(cat /confirm/content/of/file) echo $textfile
----

空白行や改行は削除され、空白で区切られたテキストファイルが表示されます。
OFS(Output Field Separator)はawk 利用される出力区切り子設定です。
====


3-2 CSVとは
[TIP]
====
ファイルの各要素が、区切り子`,`で分割されたデータをCSV(Comma Separated Value)ファイルと呼ぶ・
====


3-2 配列変数へ追記省力化
[TIP]
====
配列変数へ追記する記法の省力化

----
example_array+=("new string")
----
====

3-4 less 水平スクロール設定
[TIP]
====
操作端末(Terminal)のtty情報を取得し,その端末幅の半分づつ水平スクロールする設定を、.bashrc に追加書きする。
水平方向に最も長い行の最右端（末尾）移動には、ESC キーを押してから } キーを入力します。

* 水平スクロールに関する基本的な操作は以下の通りです：
** 水平最右端に移動: ESC → }
** 水平最左端（先頭）に戻る: ESC → {

----
echo -e 'ywidth=$(tput cols)\n
gen_ywidth=$(${ywidth/2))\n
# less -S 横スクロール有効化 -# ${gen_ywidth}
alias less='less -NMuSXR -# ${gen_ywidth}' >> ~/.bashrc
----
====

3-4 tee -a 追記オプション
[TIP]
====
-a で指定したファイルを上書きではなく、追記で出力します。ログファイルに追記する場合に便利なオプションです。
====

10-3
[TIP]
====
【注意】関数を１行で書く場合は、最後に(;)セミコロンが必要。

----
ls () { command ls -CF --color=tty $@ ; }
----
====

