
== シェルスクリプトで高速にファイル全体を読込む方法

[[personal-public-article-body]]
== コマンドパラメータの決まり

コマンド引数（ARG_MAX:コマンドに渡せる引数リストの合計バイト数には上限があり）
、以下のコマンドで確認できます。 +

....
$ getconf ARG_MAX
2097152
....

== 各シェルの情報

Ubuntu の、sh・bash・kshは以下となっています。

Ubuntu 24.04 +
CPU: Intel® Core™ i5-8279U +
MEM: 16GB +

$ ls -lh /bin/sh /bin/bash /bin/ksh /etc/alternatives/ksh
lrwxrwxrwx 1 root root       4  3月 31  2024 /bin/sh -> dash
-rwxr-xr-x 1 root root 1446024  3月 31  2024 /bin/bash
lrwxrwxrwx 1 root root      21  1月 13  2024 /bin/ksh -> /etc/alternatives/ksh
lrwxrwxrwx 1 root root      10  1月 13  2024 /etc/alternatives/ksh -> /bin/ksh93


== ファイル処理
シェルスクリプトでファイルを処理する場合、通常は一行一行処理か、ファイル全体をメモリ（（一つの変数）に読み込む場合があります。ファイルサイズによりますが、変数サイズは環境に依存することから環境により判断が必要です。ファイル全体をメモリに読み込むには +
`cat` +
を使うのが高速です。しかしながら数行程度の小さいファイルを読み込む場合は +
`read` +
でループを使って全行読み込んだ方が高速になります。これは `cat`
が外部コマンドであるため使用するたびに新たにサブシェル起動が行われるのに対して、
`read` はシェルビルトインコマンドなのでサブシェルが不要だからです。まず `cat`
と `read` でどれだけ違うかを見てみましょう。

[TIP]
====
※ データは1行100文字（１万バイト）のファイルを以下で作成します。 +
`$ base64 -w 100 /dev/urandom | head -n 行数` +
====


[.bold]#cat.exe#

....
# 第二引数が指定なしや未定義の場合、「１」のデフォルトから１００００まで出力
for i in $(seq ${2:-10000}); do
  # echo _ はファイル末尾の改行を削除されないようにするためです
  # この処理で 20% ～ 50% 程度遅くなってしまうのですが
  # ここでは原則としてファイル内容をあるがまま読み込むものとします
  mline=$(cat "$1"; echo _)
  mline=${mline%_}
done
....

[.bold]#read.exe#

....
LF="
"
for i in $(seq ${2:-10000}); do
  mline=''
  while IFS= read -r line; do
    mline="${mline}${line}${LF}"
  done < "$1"
  mline="${mline}${line}" # 最終行に改行がない場合の処理です
done
....

1行のファイル読込みを1万回繰り返した場合を5回試行する。
time コマンドの単位は秒(s)です。

....
cat.exe:
# for i in {1..10};do /usr/bin/time -f " %E real, %U user, %S sys" [sh,bash,ksh] cat.exe test001.txt ;done
sh  : 0:17.91 real,  6.32 user, 11.88 sys
      0:17.81 real,  6.20 user, 11.90 sys
      0:17.82 real,  6.23 user, 11.98 sys
      0:17.77 real,  6.20 user, 11.86 sys
      0:17.77 real,  6.16 user, 11.89 sys

bash: 0:28.37 real, 10.01 user, 19.75 sys
      0:30.29 real, 10.39 user, 21.31 sys
      0:28.71 real,  9.96 user, 20.09 sys
      0:28.58 real,  9.96 user, 19.89 sys
      0:29.23 real, 10.07 user, 20.45 sys

ksh : 0:15.91 real,  4.94 user, 11.06 sys
      0:15.15 real,  4.31 user, 10.80 sys
      0:15.99 real,  4.72 user, 11.27 sys
      0:22.52 real,  6.61 user, 16.11 sys
      0:15.17 real,  4.37 user, 10.78 sys


read.exe:
# for i in {1..5};do /usr/bin/time -f " %E real, %U user, %S sys" [sh,bash,ksh] read.exe test001.txt ;done
sh  : 0:02.11 real,  0.96 user,  1.14 sys
      0:02.00 real,  0.88 user,  1.12 sys
      0:02.00 real,  0.87 user,  1.13 sys
      0:01.99 real,  0.85 user,  1.13 sys
      0:01.99 real,  0.89 user,  1.10 sys

bash: 0:00.71 real,  0.55 user,  0.16 sys
      0:00.69 real,  0.53 user,  0.16 sys
      0:00.71 real,  0.55 user,  0.16 sys
      0:00.72 real,  0.56 user,  0.15 sys
      0:00.68 real,  0.52 user,  0.15 sys

ksh : 0:00.47 real,  0.31 user,  0.16 sys
      0:00.45 real,  0.31 user,  0.14 sys
      0:00.44 real,  0.29 user,  0.15 sys
      0:00.44 real,  0.28 user,  0.15 sys
      0:00.44 real,  0.29 user,  0.15 sys

....

100行のファイル読込みを1万回行った場合を5回試行する

....
cat.exe:
# for i in {1..5};do /usr/bin/time -f " %E real, %U user, %S sys" [sh,bash,ksh] cat.exe test100.txt ;done

sh  : 0:18.44 real,  7.26 user, 13.34 sys
      0:18.35 real,  7.34 user, 13.18 sys
      0:18.26 real,  7.31 user, 13.10 sys
      0:18.23 real,  7.20 user, 13.16 sys
      0:18.33 real,  7.20 user, 13.31 sys

bash: 0:31.62 real, 13.98 user, 20.73 sys
      0:33.21 real, 15.01 user, 21.47 sys
      0:33.32 real, 14.96 user, 21.61 sys
      0:31.70 real, 13.93 user, 20.84 sys
      0:30.63 real, 13.31 user, 20.29 sys

ksh : 0:19.20 real,  7.46 user, 11.78 sys
      0:18.82 real,  7.14 user, 11.68 sys
      0:18.69 real,  7.02 user, 11.66 sys
      0:18.10 real,  6.73 user, 11.33 sys
      0:18.28 real,  6.88 user, 11.36 sys


read.exe:
sh  : 3:15.37 real, 87.92 user,107.42 sys
      3:10.17 real, 85.07 user,105.07 sys
      3:09.73 real, 85.64 user,104.05 sys
      3:09.90 real, 85.52 user,104.36 sys
      3:10.10 real, 85.69 user,104.38 sys

bash: 3:59.11 real,235.19 user,  3.88 sys
      3:56.54 real,232.62 user,  3.88 sys
      4:34.84 real,269.54 user,  4.46 sys
      4:21.09 real,256.72 user,  4.31 sys
      4:08.27 real,244.15 user,  4.08 sys

ksh : 0:07.72 real,  7.52 user,  0.18 sys
      0:07.82 real,  7.64 user,  0.17 sys
      0:07.53 real,  7.33 user,  0.19 sys
      0:07.86 real,  7.69 user,  0.16 sys
      0:07.54 real,  7.37 user,  0.16 sys
....

このようにファイルの行数が少ない場合は `cat`
は何度もプロセスを起動するため `read`
の方が速く、逆にファイルの行数が多ければ `read` だと処理内容が増えるので
`cat` の方が速くなります。

以下、 sh(dash 0.5.12-6ubuntu5) bash (5.2.21) と ksh (93u+m)
では、`cat`・ `read`ともに ksh が顕著に早くなっています。 +
sh、bash の速度低下が顕著です。なにか検証方法に間違いがあるかもしれません。もしくはsh、bashのソースのロジックに課題があるやもしれません。 +
ファイルの行数が少なければ
`read`
の方が速いのですが（シェルや環境にもよりますが）わずか百行程度で逆転します。そのためある程度の行数があるとわかっているのであれば
`cat` を使ったほうが良いということになります。
ksh で、`read` を利用することが一番速いようです。

ということで、ここでは `cat` を使うか `read`
を使うか、シェル固有の拡張機能やアルゴリズムの工夫によってファイルの行数に大きく左右されずに安定して高速にファイルを読み込む方法の検討です。


== bash の場合

bash にはファイル全体を配列に入れることができる `readarray` (`mapfile`)
という内部（組込み・ビルドイン）コマンドが実装されています。これを使用するのが最も速いようです。 +

reaarray 補足： +
-t：末尾の改行文字（\n）を取り除く +
-n count：読み込む最大行数を count に制限する +
-s count：先頭から指定した行数分をスキップする +

ここでは性能測るためだけに利用するのですが、通常は読込んだファイル一行毎に何か処理をしたいので -t を使い改行コードを除いたものを変数に代入したほうが良い。個人の感覚によるので、意識しないと悩ませられます。

....
IFS=
readarray mline < "file"
mline="${mline[*]}" # 配列に読み込んだものを結合する
....

ただし、このコマンドは bash 4.x からしか使えないようです。bash 4.x では少し遅くなりますが
`IFS= read -r -d ""` を使用して同等のことができます。`-d ""`
は正確にはファイル全体を読み込むのではなく、区切り記号 NULL
文字を見つけるまで読み込むという意味です。原則、シェルスクリプトは
NULL 文字を扱えないので読み込むファイルには NULL
文字はないという前提です。`cat` で
NULL文字を含むファイルを読み込んだとしても（警告を出して）NULL
文字は削除されるのでファイルそのものを正確に読み込むことはできません。

....
IFS= read -r -d "" mline < "file" ||:
# ||: は終了ステータスが非ゼロの場合にそれをを無視するためのものです
# ファイルに NULL 文字が含まれてない場合は、区切り記号が
# 見つからないということなので必ず非ゼロになります
....

また末尾の改行が削除されてしまい厳密には同じではない（`mline=$(cat "file")`と同等）ので参考となりますが、以下のような書き方でもファイルを読込むことができます。 `cat`
の呼び出しは行われないので末尾の改行が不要で大きなファイルを読み込む場合は高速です。

....
mline=$(<"file")
....

1行のファイル読み込みを1万回繰り返しや、
100行のファイル読み込みを1万回繰り返した場合、

....
readarray: 0:00.00 real,  0.00 user,  0.00 sys
$(<file):  0:00.00 real,  0.00 user,  0.00 sys
....

1万行のファイル読み込みを1回だけ行った場合

....
readarray: 0:00.00 real,  0.00 user,  0.00 sys
$(<file):  0:00.00 real,  0.00 user,  0.00 sys
....

`readarray` と `$(<file)` は大幅に早くなります。


== ksh93 の場合

`ksh93` は、ファイルのシークが可能であり他のシェルにはない機能を持っています。また、Shell内の関数実装も早い時期から対応しており、ここまでの性能でも一番良い結果をだしています。 +
また `ksh93` 
ではファイルディスクリプタのシーク（読み込み位置の変更）ができ（外部コマンドを使用せずに）ファイルサイズの取得も可能なため、指定したサイズだけファイルを読み込む
`read -N サイズ`
を使うことで、色々なことが可能です。対象ファイル内容が分かるときや、何バイト目を高速に読み込むことが可能です。また、末尾の改行が削除されてしまう
`$(<"file")` も使用可能でこちらも高速です。

シークは
`<#((式))` の形式で行います。 +
例えば `<#((1000))`
のように実行すると標準入力（ファイルディスクリプタ 0）を 1000
バイト目にシークします。ただし標準入力はファイルからの入力などのシーク可能でなければならないのでパイプラインからの入力では機能しません。 +
`EOF` と `CUR`
という特殊変数が利用でき、それぞれファイルの最後と現在位置を意味します。例えば
`<#((EOF-100))`
を実行するとファイルの最後尾（EOF）から100バイト目にシークします。また
`$( <#((式)) )`'
と書くことでシーク後の位置（バイト）を取得することができます。シークに関するその他の機能はマニュアルを参照してください。
`ksh93` ではドキュメント上は `IFS="" read -r -d ""`
が使用できるようですが、実際には `-d` を指定すると `-r`
（バックスラッシュをエスケープ文字として解釈しない）が無視されてしまうバグwがありましたが `ksh93u+m` で（https://github.com/ksh93/ksh/pull/17）修正されました。


