
== Linuxでのテキストファイルへの出力コマンドまとめ


Linux環境で設定ファイルを作成する場合について、 +
以下でよく使うファイル出力コマンドをまとめる。

'''''

== テキストファイルの追記

`echo`コマンドに以下のオプションがある。
利用することで改行も利用可能である。出力に簡単で早い。
-e : バックスラッシュエスケープの解釈を有効にする
  　　\n　 改行
  　　\t   水平タブ　等
 
[source,language-bash]
ファイル出力と直接関係しないが、設定をファイル追記書込する一例とする。
less の水平スクロール有効設定、ログイン時に開いている tty の情報を取得し
その半分づつ水平スクロールする設定とするものを、.bashrc に追加書きする。

----
echo -e 'ywidth=$(tput cols)\n
gen_ywidth=$(${ywidth/2))\n
# less -S 横スクロール有効化 -# ${gen_ywidth}
alias less='less -NMuSXR -# ${gen_ywidth}' >> ~/.bashrc
----

なお、`>>`は既存ファイルに追加書きで出力する。 +
新規ファイルとして作成したい場合は`>`を使う。

[source,language-bash]
----
echo "gnome-session --session=ubuntu" > ~/.xsession
----

なお、ダブルクォーテーションで括った際に変数が含まれている場合、自動的に変数展開されてしまうので、変数を含めてファイルに出力したい場合はシングルクォーテーションで囲む。

===  シングルクォーテーションを文字列として出力

シングルクォーテーションを含めてファイルに出力したい場合は以下のように記述する。

[source,language-bash]
----
echo 'abc'\''de' > ~/temp.txt
----

[.code-block-filename]#temp.txt#

[source,code-line]
----
abc'de
----

`'\'`で`\`をエスケープ文字として認識させ、次の`'`を文字として出力する。

'''''

==  2行以上のテキストファイルを作成

複数行をまとめて出力したい場合は`cat`コマンドとヒアドキュメントを用いる。

[source,language-bash]
----
cat > ~/bin/sample.sh << EOF
#!/usr/bin/env bash

echo "Viva! Ubuntu!!"
EOF
----

echoを複数記述してファイル作成するより可読性が高くなるので2行以上で有効なものとしてヒアドキュメントがある。 +
ヒアドキュメントの開始を示すキーワードは開始と終了で同じキーワードを使えば何でもよい。

===  ヒアドキュメントを使う際に変数展開をしない

bashスクリプトなどを自動作成するようなヒアドキュメントを記述しようとすると、 +
ヒアドキュメントで変数を使いたい場合がある。 +
その場合は、開始のキーワードをシングルクォーテーションかダブルクォーテーションで囲む。

[source,language-bash]
----
cat > ~/bin/sample.sh << "EOF"
#!/usr/bin/env bash

OUTPUT_STRING="Viva! Ubuntu!!"
echo "${OUTPUT_STRING}"
EOF
----

===  ヒアドキュメントを使う際に一部変数だけ変数展開しない

一部変数だけを変数展開したくない場合は`$`記号を`\`でエスケープすればよい

[source,language-bash]
----
cat > ~/bin/sample.sh << EOF
#!/usr/bin/env bash

OUTPUT_STRING="${USER}: Viva! Ubuntu!!"
echo "\${OUTPUT_STRING}"
EOF
----

上記の場合、作成されるスクリプトでは`${USER}`はログインユーザーの名前が出力されるが、 +
`${OUTPUT_STRING}`はそのまま出力される。

===  関数内でヒアドキュメントをきれいに記述したい

ヒアドキュメントは原則として行頭に書く必要があるので関数内で記述しようとすると、 +
インデントを一つ下げて書くことになってしまうため、可読性が芳しくない。 +
ヒアドキュメントの機能で`<<`を`<<-`で記述することで行頭のハードタブを無視することができる。

[source,language-bash]
mk_script.bash

----
# vi -c "set list" mk_script.bash

#!/usr/bin/env bash↲                                                        
↲                                                                           mk_script() {↲                                                            »-»-cat > ./result.bash <<- "EOF"↲
»-»-#!/usr/bin/env bash↲                                                    ↲                                                                           »-»-OUTPUT_STRING="Hello World."↲                                           »-»-echo "${OUTPUT_STRING}"↲                                                »-»-EOF↲                                                                    }↲                                                                          ↲                                                                           mk_script↲                                                                
----

※上記のコードは、タブを表示させたくて、vi  起動時にオプション(list)を設定して起動し、タブや改行を見える形にしている。このようにタブを指定することでコードの見た目は洗練される。 + コードコピーは注意。 +
`#!/usr/bin/env bash`行から最後の`EOF`行までのインデントはタブでインデントする。

あくまで無視されるのは**ハードタブ**だけなので注意すること。 +
ハードタブは複数記述可能。+
ハードタブ以外の文字列が記述されない限りは全てのハードタブが無視される。 +
使用するエディタの設定により**ハードタブが自動的に半角スペースに置換されて入力される**こともある。 +
行頭でカーソルを移動させることによってハードタブが入力されているのか、半角スペースが入力されているのか確認すること。


===  sudoとヒアドキュメントでファイルを作成

`sudo`コマンドを組み合わせて使う場合は、`cat`とヒアドキュメントではセキュリティ上多分ファイルの作成ができない。その場合は`tee`コマンドを組み合わせることでroot権限でファイルを作成することができる。

[source,language-bash]
----
sudo tee ./result.bash << EOF > /dev/null
#!/usr/bin/env bash
echo "Viva! Ubuntu!!"
EOF
----

`> /dev/null`を記述することによって`tee`コマンドによる標準出力は捨てられるのでターミナル上には出力されない。
また、既存ファイルに追記したい場合は`-a`オプションを用いる。

[source,language-bash]
----
sudo tee -a ./result2.bash << EOF > /dev/null
echo "Viva! Unutu2!!"
EOF
----

なお、上記の方法で実行した場合は所有者がrootユーザーになってしまうので +
ユーザー権限で実行したい場合は別途以下のコマンドを実行して実行権限の付与と所有者の変更をしておく。

[source,language-bash]
----
sudo chmod +x ~/result*.bash
----

===  ヒアドキュメント以外での出力方法

`{}`で囲むと複数コマンドをまとめて実行できる。

[source,language-bash]
----
{
echo '#!/bin/bash'
echo 'echo Viva Ubuntu'
} > ~/bin/result.bash
----

`echo`を大量の記述や、シングルやダブルクォーテーションで囲むかで出力結果が変わったりと面倒な点が多いのでヒアドキュメントを使うのを推奨。 +

'''''

== テキスト出力と標準出力を両方実行

前述の`tee`コマンドで実現することができる。

[source,language-bash]
----
bash ./sample.sh 2>&1 | tee $(date +"%m%d%H%M%S")_[filename].log
----

※`2>&1`は標準エラー出力を標準出力をまとめて出力できる

'''''

