
== シェルスクリプトで高速にファイル全体を読込む方法

[[personal-public-article-body]]
== 高速ファイル読込、のはじめに

Bashの変数サイズは厳密な上限は存在せず、利用可能なメモリ（RAM）に依存するようです。実質的な入力限界は8192バイト程度となるケースもあるようです。環境変数は、1024バイト（1KB）で切り捨てられるようです。入力バッファは、 内部定義により約8192バイト。変数名の長さは 255バイト以下が推奨。 +
数値の範囲: +
32bit: (            2,147,483,647) +
64bit: (9,223,372,036,854,775,807) +
コマンド引数（ARG_MAX:コマンドに渡せる引数リストの合計バイト数には上限があり）
、以下のコマンドで確認できます。 +
Ubuntu 24.04 +
CPU: Intel® Core™ i5-8279U +
MEM: 16GB +
....
$ getconf ARG_MAX
2097152
....

シェルスクリプトでファイルを処理する場合、通常は一行一行処理か、ファイル全体をメモリ（一つの変数）に読み込む場合があります。ファイルサイズによりますが、変数サイズは環境に依存することから環境で利用方法の判断が必要です。ファイル全体をメモリに読み込むには +
`cat` +
を使うのが高速です。しかしながら数行程度の小さいファイルを読み込む場合は +
`read` +
でループを使って全行読み込んだ方が高速になります。これは `cat`
が外部コマンドであるため使用するたびに新たにサブシェル起動が行われるのに対して、
`read` はシェルビルトインコマンドなのでサブシェルが不要だからです。まず `cat`
と `read` でどれだけ違うかを見てみましょう。

※ データは1行100文字のファイルで以下で作成します。 +
`$ base64 -w 100 /dev/urandom | head -n 行数` +


[.bold]#cat.sh#

....
for i in $(seq ${2:-10000}); do
  # echo _ はファイル末尾の改行を削除されないようにするためです
  # この処理で 20% ～ 50% 程度遅くなってしまうのですが
  # ここでは原則としてファイル内容をあるがまま読み込むものとします
  data=$(cat "$1"; echo _)
  data=${data%_}
done
....

[.bold]#read.sh#

....
LF="
"
for i in $(seq ${2:-10000}); do
  data=''
  while IFS= read -r line; do
    data="${data}${line}${LF}"
  done < "$1"
  data="${data}${line}" # 最終行に改行がない場合の処理です
done
....

1行のファイル読み込みを1万回繰り返した場合

....
cat.sh:
sh  : real 0m18.278s user 0m07.316s sys 0m13.089s
bash: real 0m30.631s user 0m13.045s sys 0m20.531s
ksh : real 0m16.912s user 0m06.095s sys 0m10.779s

read.sh:
sh  : real 3m17.562s user 1m28.717s sys 1m48.791s
bash: real 3m55.748s user 3m51.822s sys 0m03.872s
ksh : real 0m07.383s user 0m07.211s sys 0m00.171s

....

1万行のファイル読み込みを1回だけ行った場合

....
cat.sh:
sh  : real 0.02 user 0.02 sys 0.00
bash: real 0.06 user 0.03 sys 0.02
ksh : real 0.03 user 0.03 sys 0.00

read.sh:
sh  : real 10.36 user 9.70 sys 0.65
bash: real 140.23 user 121.62 sys 18.57
ksh : real 3.35 user 3.32 sys 0.02
....

このようにファイルの行数が少ない場合は `cat`
は何度もプロセスを起動するため `read`
の方が速く、逆にファイルの行数が多ければ `read` だと処理内容が増えるので
`cat` の方が速くなります。ファイルの行数が少なければ
`read`の方が速いですがわずか数十行程度で逆転します。そのためある程度の行数があるとわかっているのであれば
`cat` を使ったほうが良いということになります。

`cat` を使うか `read`を使うか判断するために、シェル固有の拡張機能やアルゴリズムの工夫によって改善し、ファイルの行数に大きく左右されずに安定して高速にファイルを読み込む方法を紹介します。

== bash の場合

bash にはファイル全体を配列に入れることができる `readarray` (`mapfile`)
というコマンドが実装されています。これを使用するのが最も速いようです。

....
IFS=
readarray data < "file"
data="${data[*]}" # 配列に読み込んだものを結合する
....

ただし、このコマンドは bash 4.x からしか使えません。 +
bash 4.x では少し遅くなりますが +
`IFS= read -r -d ""` を使用して同等のことができます。`-d ""`
は正確にはファイル全体を読み込むのではなく、区切り記号 NULL
文字を見つけるまで読み込むという意味です。原則としてシェルスクリプトは
NULL 文字を扱えないので読み込むファイルには NULL
文字はないという前提です。`cat` で
NULL文字を含むファイルを読み込んだとしても（警告を出して）NULL
文字は削除されるのでどちらにしろ正しく扱えません。

....
IFS= read -r -d "" data < "file" ||:
# ||: は終了ステータスが非ゼロの場合にそれをを無視するためのものです
# ファイルに NULL 文字が含まれてない場合は、区切り記号が
# 見つからないということなので必ず非ゼロになります
....

また末尾の改行が削除されてしまい厳密には同じではない（`data=$(cat "file")`と同等）ので参考となりますが、以下のような書き方でもファイルを読み込むことができます。`cat`
の呼び出しは行われないので末尾の改行が不要で大きなファイルを読み込む場合は高速です。

....
data=$(<"file")
....

1行のファイル読み込みを1万回繰り返した場合

....
cat:       real 28.77 user 21.02 sys 8.50
read:      real  0.62 user  0.50 sys 0.12
readarray: real  0.38 user  0.32 sys 0.06
read -d:   real  1.66 user  1.01 sys 0.65
array:     real  0.78 user  0.60 sys 0.16 
$(<file):  real  7.26 user  5.61 sys 2.41 
....

1万行のファイル読み込みを1回だけ行った場合

....
cat:       real 0.06 user 0.03 sys 0.02
read:      real 140.23 user 121.62 sys 18.57
readarray: real 0.06 user 0.05 sys 0.00
read -d:   real 1.38 user 0.76 sys 0.62
array:     real 9.01 user 5.28 sys 3.56 
$(<file):  real 0.07 user 0.07 sys 0.02 
....

`readarray`
を使用するとファイルの行数が少ない場合の速度が改善されます。`read -d`
はファイルの行数によって `cat` と `read`
に勝ったり負けたりしていますが、どちらも大幅な速度低下がないので総合的に見れば優れています。


== ksh93 の場合

ksh93(https://github.com/ksh93/ksh/pull/17[修正]) は、 `IFS="" read -r -d ""`
が使用できます。ksh93ではファイルディスクリプタのシーク（読込み位置の変更）が可能で（外部コマンドを使用せずに）ファイルサイズの取得もできるため、これと指定したサイズだけファイルを読み込む
`read -N サイズ`
を使うことで、ファイル全体を高速に読み込むことが可能です。また、末尾の改行が削除されてしまう
`$(<"file")` も使用可能でこちらも高速です。

....
{ read -N "$(<#((EOF)))" data <#((0)); } <"file"
....

ファイルのシークは他のシェルにはない珍しい機能なので補足します。シークは
`<#((式))` という形で行います。例えば `<#((1000))`
のように実行すると標準入力（ファイルディスクリプタ 0）を 1000
バイト目にシークします。ただし標準入力はファイルからの入力などのシーク可能でなければならないのでパイプラインからの入力では機能しません。`EOF`と `CUR`という特殊変数が利用でき、それぞれファイルの最後と現在位置を意味します。例えば
`<#((EOF-100))`
を実行するとファイルの後ろから100バイト目にシークします。また
`$( <#((式)) )`'
と書くことでシーク後の位置（バイト）を取得することができます。シークに関するその他の機能はマニュアルを参照してください。

上記のコードでは「`<"file"`
でファイルを標準入力に変更」し「`$(<#((EOF)))` で ファイルを EOF
までシークしてその位置を取得」し「` <#((0))`
でファイルの先頭に再度シーク」してファイル全体（EOFの位置まで）を読み込むという処理を行っています。

1行のファイル読み込みを1万回繰り返した場合

....
cat :     real 15.38 user 11.20 sys 4.55
read:     real  0.45 user  0.34 sys 0.11
read -N:  real  0.04 user  0.00 sys 0.00
array:    real  0.51 user  0.36 sys 0.15 
$(<file): real  0.16 user  0.07 sys 0.08 
....

1万行のファイル読み込みを1回だけ行った場合

....
cat:      real  0.03 user  0.03 sys 0.00
read:     real  3.35 user  3.32 sys 0.02
read -N:  real  0.02 user  0.01 sys 0.00
array:    real  0.51 user  0.36 sys 0.15
$(<file): real  0.00 user  0.00 sys 0.00
....


