
== シェルスクリプトの共通関数・定数の管理


[[personal-public-article-body]]
=== シェルスクリプトの共通関数 

環境構築・設定ファイル等のスクリプトを１つのリポジトリ（https://github.com/等）にまとめることが可能な環境なら共通関数は有効です。登録・管理・再利用する場合、条件とか情報整理が重要です。shellcheckerを自動的にかけるとかあれば安心して利用可能かもしれません。 +


一人で作成を積み重ねたものを無駄にせず、複数人で使う場合は情報共有・整理整頓が重要です。共通でよく使う定数や共通関数をまとめてGithubで管理すればサービスが続く限り有効です。+
以下、画面出力msg を色付けしたい場合の共通関数です。↓

[.bold]#coloring_msg.bash#

....
#!/usr/bin/env bash
set -Ceux
# -C : リダイレクト「＞」を使ってすでにあるファイルを上書きすることを禁止
# -e : bashで利用可能なtest構文、 fileの存在確認。スクリプト中のコマンドエラー時に実行停止
# -u : 同上。 set-uidビット・ fileが存在し、かつset-uid-bitが立っているか確認
# -x : スクリプト実行内容を画面出力する

declare -A ESV

PSV="PSV" # Print Shell-Value

# 他ファイル定義の関数呼出し保法例
# source PSV_FUNCTIONS
# . PSV_FUNCTIONS

function PSV_INIT() {
        RED_MSG $0
  ### シェル変数打出しのデバッグ文出力ための前処理
  # 打出し関数を利用する行を取得し、表示したい変数名を打出しに利用したい
  # sed や tail,head （千行以上ではtail・headが早い)でPSHVAL行を取得可能だがgrep -n で検索
  STPOUT=(`grep -n ${PSV} $0 | grep -v "^[0-9]*:[ \t]*#" | grep -v function | grep -v "PSV=" | tr -s " " | cut -d" " -f1-`)
  
  # ダブルクォーテーションで括ると改行を入れる
  for i in "${STPOUT[@]}"; do
    # シェル変数の正規表現利用は以下のようにする。expre 比較1:比較2 もある
    # シェル変数が配列"[]"を含むか判定する
    if [[ $i =~ [0-9]*: ]] ;then
      GNUM=`echo $i | cut -d":" -f1`; TMPSV=`echo $i | cut -d":" -f2`
      if [[ -v $TMPSV ]] ;then
        STPOUT01[$GNUM]+=" $GNUM"; STPOUT01[$GNUM]+=" $TMPSV"
      fi
    elif [[ $i =~ \[@\] ]] ;then
      ESV[$GNUM]+=" ARRAYALL-${i}"; STPOUT01[$GNUM]+=" ${i}"
    elif [[ $i =~ \[[0-9]*\] ]] ;then
      ESV[$GNUM]+=" ARRAY-${i}"; STPOUT01[$GNUM]+=" ${i}"
    else
      if [[ ${i} =~ $PSV ]] ;then
        :
      else
        # 連想配列にスペースを入れながら追加する
        # result_ex. ESV[22]="PSHVAL $BJ2 $BJ3 .." 
        ESV[$GNUM]+=" ${i}"; STPOUT01[$GNUM]+=" ${i}"
      fi
    fi
  done
}

function PSV() {
  # 打出し変数表示のためのインデックス値
  CNT=0;
  # 呼出された行番号を改行無しで表示する
  echo -n "==> Call Line: ${BASH_LINENO[0]}  "
  # 配列変数の打出しの場合の対処
  DVN=(${ESV[${BASH_LINENO[0]}]})
  # この関数をコールされた引数の表示処理をする。引数の数は可変なので以下ループで処理
  for i in $@; do
    # 呼出された行番号表示。呼出しの打出し変数を表示する（大変だった）
    # 連想配列ESV[行番号]="PSHVAL $BJ2 $BJ2" をスペースで分割する。cf. ("${ESV[${dim}]}")
    # ESV[行番号]="PSHVAL $fsch3 $FILENAME $CFNAME"のため以下
    echo -n "${DVN[${CNT}]}=[${i}] "
    # CNT はコールするパラメータ変数名表示のため記述
    CNT=`expr $CNT + 1`
  done
  # 強制的に改行を挿入。デバッグ用変数打出しを目立たせるため
  echo
}

function del_kakko() {
  tr -d "(" < $1 > $APCHANLDIR/ontheway01-1.txt; tr -d ")" < $APCHANLDIR/ontheway01-1.txt > $2
  rm $APCHANLDIR/ontheway01-1.txt
}

# Terminal のコマンドラインの色情報
#
# NC='\033[0m'  テキストの色をデフォルトにリセットする変数を定義
# 出力色の変更
# 先述した \e[0m でリセット可能。
#
# 出力色の変更（拡張）
# 文字色          背景色          内容
# \e[38;5;nm      \e[48;5;nm      nを0～255のカラーコードを指定
# \e[38;2;r;g;bm  \e[48;2;r;g;bm  RGBでのカラーコードを指定
# 注：ターミナルによって対応してる/してないが分かれる
# （対応端末少ない）
# 
# 文字出力例: 太字・薄字・斜字・下線字・背景字・黒字・？
# 文字色      背景色  内容
# \e[1m               太字
# \e[2m               薄く表示
# \e[3m               イタリック
# \e[4m               アンダーライン
# \e[5m               ブリンク
# \e[6m               高速ブリンク
# \e[7m               文字色と背景色の反転
# \e[8m               表示を隠す（コピペ可能）
# \e[9m　　　　　　　　取り消し
# \e[31m      \e[41m  赤
# \e[32m      \e[42m  緑
# \e[33m      \e[43m  黄色
# \e[34m      \e[44m  青
# \e[35m      \e[45m  マゼンダ
# \e[36m      \e[46m  シアン
# \e[37m      \e[47m  白


function ECHO_TXTRED() {
  echo -e '\e[31m'$1'\e[0m'
}
function ECHO_TXTGREEN() {
  echo -e '\e[32m'$1'\e[0m'
}
function ECHO_TXTYELLOW() {
  echo -e '\e[33m'$1'\e[0m'
}
function ECHO_TXTBLUE() {
  echo -e '\e[34m'$1'\e[0m'
}
function ECHO_TXTMAGENDA() {
  echo -e '\e[35m'$1'\e[0m'
}
function ECHO_TXTCYAN() {
  echo -e '\e[36m'$1'\e[0m'
  echo_color cyan "$@"
}
function ECHO_TXTWHITE() {
  echo -e '\e[37m'$1'\e[0m'
}
function ECHO_WEBERR() {
  echo_color red "<b>ERROR</b>: " "$@"
}
function ECHO_TXTLOG() {
  echo_color magenta "LOG: " "$@"
}

# Terminalで色をつける
# エスケープシーケンスを利用                                                                    #
echo_color() {
  case "$1" in
    red)
      color_code='\e[31m'
      ;;
    green)
      color_code='\e[32m'
      ;;
    yellow)
      color_code='\e[33m'
      ;;
    magenta)
      color_code='\e[35m'
      ;;
    cyan)
      color_code='\e[36m'
      ;;
    *)
      color_code='\e[37m'                                                                       ;;                                       
  esac
  shift
#      カラーコード  msg リセット(≒\e[0m)
  echo "$color_code""$@"'\e[m' 

}


....


== 外部スクリプトの有効性

外部スクリプトに対してできることは、

* 実行する
* `.`（ドット）コマンドで読み込む。Bashでは`source`コマンド利用。

の2択です。 +
「.」の実行は実行するスクリプトの中で記述した変数や関数は、自分が作成したスクリプトに取込めないので、ドットコマンドで読み込んでみます。

bashのシェルスクリプトでは、他ファイルに作成した関数をsourceで取り込めます。
以下はロードする例。

[.bold]#main.bash#

....
#!/usr/bin/env bash
set -Ceu

# プロジェクトフォルダの絶対パス取得
cd "$(dirname "$0")"  # このスクリプトがあるフォルダに移動
cd ./                 # ＝ここをプロジェクトフォルダとします。
dir_project=$(pwd)

# 共通関数部分読み込み
. "$dir_project/coloring_msg.bash"

# 使用
ECHO_TXTYELLOW  'わぁい'"$SHELL"' 、'"$USER"'大好き'
# 出力文字種類・文字色・反転背景色の確認。ブレーズ変数
# 太字とイタリック体と反転文字をわかり易く「BASH」比較表示

echo "太字 薄くItalc  UL_ Blnq  高B 反転 隠蔽 取消"                                     # 文字・文字色・背景色指定出力確認                                                      for i in {1..9} {30..37} {40..47}; do                                                       printf '\e[%dmBASH\e[m ' $i                                                             if [[ "$i" -eq "9" ]];then                                                                echo -en "\n"                                                                           echo -en "色\n  黒   赤   緑   黄   青   朱   水   白\n"                              fi                                                                                      if [[ "$i" -eq "37" ]];then                                                               echo -en "\n"                                                                           echo -en "反転\n  黒   赤   緑   黄   青   朱   水   白\n"                            fi                                                                                  done                                                                                    echo　# 改行挿入  


できました。

