
== シェルスクリプトのロギングを楽にする

[[personal-public-article-body]]
=== 背景

cronの仕込むShellScriptのデバッグでは、echoでログ出力’はよくある話です。 +
ちょっとした関数を用意しておけばログは楽で汎用的に取れるのでまとめます。 +

==== log関数をつくる

=== コード
たった11行。 +
使う前に *`LOGFILE`変数を変数利用前に設定が条件です。* +
ログレベルみたいなものがほしい場合、INFO/WARN/ERROR/EMERGを第１引数で渡し、
第１引数がない場合はINFOとか決めた関数を作ればよい。
共通関数化せずローカルで使うほうが好都合で、色々なスクリプトから呼ばれた場合など簡単に考えたものは後半にあります。

【前半】 +

=== LOGtest.bash
....
#!/usr/bin/env bash -
# 書込み権限ある場所のファイル名設定は必須 'LOGFILE'
LOGFILE="/home/username/LOG/ShellScript01.log"

readonly SSNAME=${0##*/} +
# ShellScript名をパスを含む指定で起動しても最長のパス名を削除する変数操作
function log() {
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') ${SSNAME} (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $@" | tee -a ${LOGFILE}
}
....

出力フォーマットはecho文なので適当に直してください。`-e`オプションも改行\nも使わないから不要かもしれません・・・ +

=== ログのフォーマット

上記実装だとこのように出力される。

....
2025-08-27 18:58:14 LOGop.bash test.sh (LOGop.sh:5:main) message
....

途中の()の中身は、コロン区切りでこんな感じ。

* log関数を呼び出した *スクリプト名*
* log関数を呼び出したスクリプトの *行番号*
* log関数を呼び出した *関数名*

ホスト名は付けていないので、必要なら`${HOSTNAME}`とかを入れると良いんじゃないかと。 +
大元の実行ファイル名部分は不要だというなら、`${fname}`を削ってください。

=== 使い方

echoと一緒。

....
log "message"
....

=== 単一スクリプトでの実装例

先ほどのlog関数を実装したスクリプトを書いてみる。

==== 実装

`LOGFILE`変数（どこにログを格納するか）は最初に宣言している。 +
mainの途中に関数実装が挟まる素敵な例。

[.bold]#LOGop.bash#

....
#!/usr/bin/env bash -
# 上記「bash -」は、ログインシェルとして動作。これは、ログイン時に
# 読込む/etc/profileや~/.bash_profile、~/.profile等の初期化ファイルを読込み、# 環境変数や設定をログイン時の状態として初期化する動作です

readonly LOGFILE="/tmp/${0##*/}.log"

readonly PROCNAME=${0##*/}
function log() {
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%dT%H:%M:%S') ${PROCNAME} (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $@" | tee -a ${LOGFILE}
}


#
# MAIN
#

log "This is Test msg 0"
log "Test 1"
log "Test 2"

function logtestfunc() {
  log "LOG from logtestfunc"
}

logtestfunc
....

==== 実行

....
$ cd /tmp
$ cat LOGop.bash.log
2025-08-27T15:56:23 LOGop.bash (LOGop.bash:13:main) This is test msg 0
2025-08-27T15:56:23 LOGop.bash (LOGop.bash:14:main) Test 1
2025-08-27T15:56:23 LOGop.bash (LOGop.bash:15:main) Test 2
2025-08-27T15:56:23 LOGop.bash (LOGop.bash:18:logtestfunc) LOG from logtestfunc function
....

コンソールにも出力し、ログにも記録する。 +
プロセス名とかスクリプト名が冗長と思うでしょうが、他のスクリプトから呼ばれた場合は有効かな・・・


【後半】 +

=== ライブラリ風の実装例

今度はライブラリのように、`LOGlib.bash`を作成してみる。

==== 実装(ライブラリ)

`LOGFILE`変数は、スクリプト毎に定義できるようにここでは定義していない。

[.bold]#LOGlib.bash#

....
#!/bin/bash -
# You must set 'LOGFILE'
readonly PROCNAME=${0##*/}
function log() {
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%dT%H:%M:%S') ${PROCNAME} (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $@" | tee -a ${LOGFILE}
}
....

==== 実装(スクリプト本体)

作った`LOGlib.bash`を使う`LIBtest.bash`を書く。 +
`LOGFILE`変数は、ライブラリを使う *本体スクリプト側で定義する*
例としている。

[.bold]#LIBtest.bash#

....
#!/bin/bash -
LOGFILE="/tmp/test.log"
. /tmp/LIBop.bash

log "test message from main"

function logtest() {
  log "test message from func"
}

logtest

. /tmp/libtest_sub.sh
sub_command
....

最後の2行で呼び出している`LIB_test.bash`および`sub_commmand`の実装はこちら。

[.bold]#LIBop_sub.sh#

....
#!/bin/bash -

function sub_command() {
  log "This is sub script"
}
....

試験用のため簡易な作成と実装です。

==== 実行

....
$ ./libtest.sh
2025-08-27T18:58:14 libtest.sh (libtest.sh:5:main) test message from main
2025-08-27T18:58:14 libtest.sh (libtest.sh:8:logtest) test message from func
2025-08-27T18:58:14 libtest.sh (libtest_sub.sh:4:sub_command) This is sub script

$ cat /tmp/test.log
2025-08-27T18:58:14 libtest.sh (libtest.sh:5:main) test message from main
2025-08-27T18:58:14 libtest.sh (libtest.sh:8:logtest) test message from func
2025-08-27T18:58:14 libtest.sh (libtest_sub.sh:4:sub_command) This is sub script
....

どのスクリプトファイルのどの位置から呼ばれたかわかるので、複数人でメンテしているようなバッチに向いている出力になったと思う。


